// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'

    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'BrowserKey',
    appId: '1:879909987185:web:35f8be8a2715167a9e0cd0',
    messagingSenderId: '879909987185',
    projectId: 'uniride-db-a468e',
    authDomain: 'uniride-db-a468e.firebaseapp.com',
    storageBucket: 'uniride-db-a468e.appspot.com',
    measurementId: 'G-V1CS1TFQH7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AndroidKey',
    appId: '1:879909987185:android:e6c464acc469fa729e0cd0',
    messagingSenderId: '879909987185',
    projectId: 'uniride-db-a468e',
    storageBucket: 'uniride-db-a468e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'IosKey',
    appId: '1:879909987185:ios:eaa9e0e61903614d9e0cd0',
    messagingSenderId: '879909987185',
    projectId: 'uniride-db-a468e',
    storageBucket: 'uniride-db-a468e.appspot.com',
    iosClientId: '879909987185-9v22dkjt794e055ii51ciui0s8q4rs90.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniride',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'IosKey',
    appId: '1:879909987185:ios:80aaabc3c1a0ade09e0cd0',
    messagingSenderId: '879909987185',
    projectId: 'uniride-db-a468e',
    storageBucket: 'uniride-db-a468e.appspot.com',
    iosClientId: '879909987185-9p7iummg2luu98srove7d18b3vbl2tuv.apps.googleusercontent.com',
    iosBundleId: 'com.example.uniride.RunnerTests',
  );
}
